### PR TITLE
Remove MeasureDuration and Kafka module

### PR DESCRIPTION
**Pull request by Z1kkurat**
This is a breaking change that will require a new major release.
- `MeasureDuration` has been removed in favor of the same implementation from `cats-helper` (since `3.5.0`): https://github.com/evolution-gaming/cats-helper/blob/master/core/src/main/scala/com/evolutiongaming/catshelper/MeasureDuration.scala
- `kafka` module has been removed, and the same functionality is now available directly in `skafka-metrics` (since `15.1.0`): https://github.com/evolution-gaming/skafka/blob/master/modules/metrics/src/main/scala/com/evolutiongaming/skafka/metrics/KafkaMetricsCollector.scala
- dependency to `skafka` has been removed, thus resolving https://github.com/evolution-gaming/skafka/issues/338

### CODE REVIEW

**Comment by t3hnar** [comment]
MR looks ok, however I'd propose to make one more step in between - create release with this code being deprecated and deprecation messages tells where to get the new code

**Comment by Z1kkurat** [comment]
> MR looks ok, however I'd propose to make one more step in between - create release with this code being deprecated and deprecation messages tells where to get the new code

A good idea. Please see https://github.com/evolution-gaming/smetrics/pull/252 and https://github.com/evolution-gaming/smetrics/pull/253

**Comment by Z1kkurat** [comment]
> MR looks ok, however I'd propose to make one more step in between - create release with this code being deprecated and deprecation messages tells where to get the new code

Released 1.1.0 and 0.4.0

**Comment by Z1kkurat** [comment]
@t3hnar I'll merge it if no objections.

**Review by t3hnar — APPROVED** [review]

**Pull request merged**
